# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from xronos.proto import spec_pb2 as xronos_dot_proto_dot_spec__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in xronos/proto/spec_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DrafterStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
                '/xronos.spec.Drafter/Health',
                request_serializer=xronos_dot_proto_dot_spec__pb2.HealthRequest.SerializeToString,
                response_deserializer=xronos_dot_proto_dot_spec__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.SetFrequency = channel.unary_unary(
                '/xronos.spec.Drafter/SetFrequency',
                request_serializer=xronos_dot_proto_dot_spec__pb2.SetFrequencyRequest.SerializeToString,
                response_deserializer=xronos_dot_proto_dot_spec__pb2.SetFrequencyResponse.FromString,
                _registered_method=True)
        self.IdlePower = channel.unary_unary(
                '/xronos.spec.Drafter/IdlePower',
                request_serializer=xronos_dot_proto_dot_spec__pb2.IdlePowerRequest.SerializeToString,
                response_deserializer=xronos_dot_proto_dot_spec__pb2.IdlePowerResponse.FromString,
                _registered_method=True)
        self.InitSession = channel.unary_unary(
                '/xronos.spec.Drafter/InitSession',
                request_serializer=xronos_dot_proto_dot_spec__pb2.InitSessionRequest.SerializeToString,
                response_deserializer=xronos_dot_proto_dot_spec__pb2.InitSessionResponse.FromString,
                _registered_method=True)
        self.Draft = channel.unary_unary(
                '/xronos.spec.Drafter/Draft',
                request_serializer=xronos_dot_proto_dot_spec__pb2.DraftRequest.SerializeToString,
                response_deserializer=xronos_dot_proto_dot_spec__pb2.DraftResponse.FromString,
                _registered_method=True)
        self.Commit = channel.unary_unary(
                '/xronos.spec.Drafter/Commit',
                request_serializer=xronos_dot_proto_dot_spec__pb2.CommitRequest.SerializeToString,
                response_deserializer=xronos_dot_proto_dot_spec__pb2.CommitResponse.FromString,
                _registered_method=True)
        self.ResetSession = channel.unary_unary(
                '/xronos.spec.Drafter/ResetSession',
                request_serializer=xronos_dot_proto_dot_spec__pb2.ResetSessionRequest.SerializeToString,
                response_deserializer=xronos_dot_proto_dot_spec__pb2.ResetSessionResponse.FromString,
                _registered_method=True)


class DrafterServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetFrequency(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IdlePower(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InitSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Draft(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Commit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResetSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DrafterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=xronos_dot_proto_dot_spec__pb2.HealthRequest.FromString,
                    response_serializer=xronos_dot_proto_dot_spec__pb2.HealthResponse.SerializeToString,
            ),
            'SetFrequency': grpc.unary_unary_rpc_method_handler(
                    servicer.SetFrequency,
                    request_deserializer=xronos_dot_proto_dot_spec__pb2.SetFrequencyRequest.FromString,
                    response_serializer=xronos_dot_proto_dot_spec__pb2.SetFrequencyResponse.SerializeToString,
            ),
            'IdlePower': grpc.unary_unary_rpc_method_handler(
                    servicer.IdlePower,
                    request_deserializer=xronos_dot_proto_dot_spec__pb2.IdlePowerRequest.FromString,
                    response_serializer=xronos_dot_proto_dot_spec__pb2.IdlePowerResponse.SerializeToString,
            ),
            'InitSession': grpc.unary_unary_rpc_method_handler(
                    servicer.InitSession,
                    request_deserializer=xronos_dot_proto_dot_spec__pb2.InitSessionRequest.FromString,
                    response_serializer=xronos_dot_proto_dot_spec__pb2.InitSessionResponse.SerializeToString,
            ),
            'Draft': grpc.unary_unary_rpc_method_handler(
                    servicer.Draft,
                    request_deserializer=xronos_dot_proto_dot_spec__pb2.DraftRequest.FromString,
                    response_serializer=xronos_dot_proto_dot_spec__pb2.DraftResponse.SerializeToString,
            ),
            'Commit': grpc.unary_unary_rpc_method_handler(
                    servicer.Commit,
                    request_deserializer=xronos_dot_proto_dot_spec__pb2.CommitRequest.FromString,
                    response_serializer=xronos_dot_proto_dot_spec__pb2.CommitResponse.SerializeToString,
            ),
            'ResetSession': grpc.unary_unary_rpc_method_handler(
                    servicer.ResetSession,
                    request_deserializer=xronos_dot_proto_dot_spec__pb2.ResetSessionRequest.FromString,
                    response_serializer=xronos_dot_proto_dot_spec__pb2.ResetSessionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'xronos.spec.Drafter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('xronos.spec.Drafter', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Drafter(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xronos.spec.Drafter/Health',
            xronos_dot_proto_dot_spec__pb2.HealthRequest.SerializeToString,
            xronos_dot_proto_dot_spec__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetFrequency(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xronos.spec.Drafter/SetFrequency',
            xronos_dot_proto_dot_spec__pb2.SetFrequencyRequest.SerializeToString,
            xronos_dot_proto_dot_spec__pb2.SetFrequencyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IdlePower(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xronos.spec.Drafter/IdlePower',
            xronos_dot_proto_dot_spec__pb2.IdlePowerRequest.SerializeToString,
            xronos_dot_proto_dot_spec__pb2.IdlePowerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InitSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xronos.spec.Drafter/InitSession',
            xronos_dot_proto_dot_spec__pb2.InitSessionRequest.SerializeToString,
            xronos_dot_proto_dot_spec__pb2.InitSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Draft(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xronos.spec.Drafter/Draft',
            xronos_dot_proto_dot_spec__pb2.DraftRequest.SerializeToString,
            xronos_dot_proto_dot_spec__pb2.DraftResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Commit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xronos.spec.Drafter/Commit',
            xronos_dot_proto_dot_spec__pb2.CommitRequest.SerializeToString,
            xronos_dot_proto_dot_spec__pb2.CommitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResetSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xronos.spec.Drafter/ResetSession',
            xronos_dot_proto_dot_spec__pb2.ResetSessionRequest.SerializeToString,
            xronos_dot_proto_dot_spec__pb2.ResetSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class VerifierStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
                '/xronos.spec.Verifier/Health',
                request_serializer=xronos_dot_proto_dot_spec__pb2.HealthRequest.SerializeToString,
                response_deserializer=xronos_dot_proto_dot_spec__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.SetFrequency = channel.unary_unary(
                '/xronos.spec.Verifier/SetFrequency',
                request_serializer=xronos_dot_proto_dot_spec__pb2.SetFrequencyRequest.SerializeToString,
                response_deserializer=xronos_dot_proto_dot_spec__pb2.SetFrequencyResponse.FromString,
                _registered_method=True)
        self.IdlePower = channel.unary_unary(
                '/xronos.spec.Verifier/IdlePower',
                request_serializer=xronos_dot_proto_dot_spec__pb2.IdlePowerRequest.SerializeToString,
                response_deserializer=xronos_dot_proto_dot_spec__pb2.IdlePowerResponse.FromString,
                _registered_method=True)
        self.InitSession = channel.unary_unary(
                '/xronos.spec.Verifier/InitSession',
                request_serializer=xronos_dot_proto_dot_spec__pb2.InitSessionRequest.SerializeToString,
                response_deserializer=xronos_dot_proto_dot_spec__pb2.InitSessionResponse.FromString,
                _registered_method=True)
        self.Verify = channel.unary_unary(
                '/xronos.spec.Verifier/Verify',
                request_serializer=xronos_dot_proto_dot_spec__pb2.VerifyRequest.SerializeToString,
                response_deserializer=xronos_dot_proto_dot_spec__pb2.VerifyResponse.FromString,
                _registered_method=True)
        self.Generate = channel.unary_unary(
                '/xronos.spec.Verifier/Generate',
                request_serializer=xronos_dot_proto_dot_spec__pb2.GenerateRequest.SerializeToString,
                response_deserializer=xronos_dot_proto_dot_spec__pb2.GenerateResponse.FromString,
                _registered_method=True)
        self.ResetSession = channel.unary_unary(
                '/xronos.spec.Verifier/ResetSession',
                request_serializer=xronos_dot_proto_dot_spec__pb2.ResetSessionRequest.SerializeToString,
                response_deserializer=xronos_dot_proto_dot_spec__pb2.ResetSessionResponse.FromString,
                _registered_method=True)


class VerifierServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetFrequency(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IdlePower(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InitSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Verify(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Generate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResetSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VerifierServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=xronos_dot_proto_dot_spec__pb2.HealthRequest.FromString,
                    response_serializer=xronos_dot_proto_dot_spec__pb2.HealthResponse.SerializeToString,
            ),
            'SetFrequency': grpc.unary_unary_rpc_method_handler(
                    servicer.SetFrequency,
                    request_deserializer=xronos_dot_proto_dot_spec__pb2.SetFrequencyRequest.FromString,
                    response_serializer=xronos_dot_proto_dot_spec__pb2.SetFrequencyResponse.SerializeToString,
            ),
            'IdlePower': grpc.unary_unary_rpc_method_handler(
                    servicer.IdlePower,
                    request_deserializer=xronos_dot_proto_dot_spec__pb2.IdlePowerRequest.FromString,
                    response_serializer=xronos_dot_proto_dot_spec__pb2.IdlePowerResponse.SerializeToString,
            ),
            'InitSession': grpc.unary_unary_rpc_method_handler(
                    servicer.InitSession,
                    request_deserializer=xronos_dot_proto_dot_spec__pb2.InitSessionRequest.FromString,
                    response_serializer=xronos_dot_proto_dot_spec__pb2.InitSessionResponse.SerializeToString,
            ),
            'Verify': grpc.unary_unary_rpc_method_handler(
                    servicer.Verify,
                    request_deserializer=xronos_dot_proto_dot_spec__pb2.VerifyRequest.FromString,
                    response_serializer=xronos_dot_proto_dot_spec__pb2.VerifyResponse.SerializeToString,
            ),
            'Generate': grpc.unary_unary_rpc_method_handler(
                    servicer.Generate,
                    request_deserializer=xronos_dot_proto_dot_spec__pb2.GenerateRequest.FromString,
                    response_serializer=xronos_dot_proto_dot_spec__pb2.GenerateResponse.SerializeToString,
            ),
            'ResetSession': grpc.unary_unary_rpc_method_handler(
                    servicer.ResetSession,
                    request_deserializer=xronos_dot_proto_dot_spec__pb2.ResetSessionRequest.FromString,
                    response_serializer=xronos_dot_proto_dot_spec__pb2.ResetSessionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'xronos.spec.Verifier', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('xronos.spec.Verifier', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Verifier(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xronos.spec.Verifier/Health',
            xronos_dot_proto_dot_spec__pb2.HealthRequest.SerializeToString,
            xronos_dot_proto_dot_spec__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetFrequency(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xronos.spec.Verifier/SetFrequency',
            xronos_dot_proto_dot_spec__pb2.SetFrequencyRequest.SerializeToString,
            xronos_dot_proto_dot_spec__pb2.SetFrequencyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IdlePower(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xronos.spec.Verifier/IdlePower',
            xronos_dot_proto_dot_spec__pb2.IdlePowerRequest.SerializeToString,
            xronos_dot_proto_dot_spec__pb2.IdlePowerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InitSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xronos.spec.Verifier/InitSession',
            xronos_dot_proto_dot_spec__pb2.InitSessionRequest.SerializeToString,
            xronos_dot_proto_dot_spec__pb2.InitSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Verify(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xronos.spec.Verifier/Verify',
            xronos_dot_proto_dot_spec__pb2.VerifyRequest.SerializeToString,
            xronos_dot_proto_dot_spec__pb2.VerifyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Generate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xronos.spec.Verifier/Generate',
            xronos_dot_proto_dot_spec__pb2.GenerateRequest.SerializeToString,
            xronos_dot_proto_dot_spec__pb2.GenerateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResetSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xronos.spec.Verifier/ResetSession',
            xronos_dot_proto_dot_spec__pb2.ResetSessionRequest.SerializeToString,
            xronos_dot_proto_dot_spec__pb2.ResetSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
