"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class HealthRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___HealthRequest = HealthRequest

@typing.final
class HealthResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class MetadataEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    OK_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    MODEL_FIELD_NUMBER: builtins.int
    DEVICE_FIELD_NUMBER: builtins.int
    METADATA_FIELD_NUMBER: builtins.int
    ok: builtins.bool
    message: builtins.str
    model: builtins.str
    device: builtins.str
    @property
    def metadata(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]: ...
    def __init__(
        self,
        *,
        ok: builtins.bool = ...,
        message: builtins.str = ...,
        model: builtins.str = ...,
        device: builtins.str = ...,
        metadata: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["device", b"device", "message", b"message", "metadata", b"metadata", "model", b"model", "ok", b"ok"]) -> None: ...

global___HealthResponse = HealthResponse

@typing.final
class RailEnergy(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RAIL_FIELD_NUMBER: builtins.int
    MEAN_POWER_MW_FIELD_NUMBER: builtins.int
    ENERGY_MJ_FIELD_NUMBER: builtins.int
    rail: builtins.str
    mean_power_mw: builtins.float
    energy_mj: builtins.float
    def __init__(
        self,
        *,
        rail: builtins.str = ...,
        mean_power_mw: builtins.float = ...,
        energy_mj: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["energy_mj", b"energy_mj", "mean_power_mw", b"mean_power_mw", "rail", b"rail"]) -> None: ...

global___RailEnergy = RailEnergy

@typing.final
class SetFrequencyRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    JETSON_GPU_FREQ_HZ_FIELD_NUMBER: builtins.int
    NVIDIA_SMI_GPU_CLOCK_MHZ_FIELD_NUMBER: builtins.int
    jetson_gpu_freq_hz: builtins.int
    nvidia_smi_gpu_clock_mhz: builtins.int
    def __init__(
        self,
        *,
        jetson_gpu_freq_hz: builtins.int = ...,
        nvidia_smi_gpu_clock_mhz: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["jetson_gpu_freq_hz", b"jetson_gpu_freq_hz", "nvidia_smi_gpu_clock_mhz", b"nvidia_smi_gpu_clock_mhz"]) -> None: ...

global___SetFrequencyRequest = SetFrequencyRequest

@typing.final
class SetFrequencyResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class MetadataEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    OK_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    METADATA_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    ok: builtins.bool
    message: builtins.str
    error: builtins.str
    @property
    def metadata(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]: ...
    def __init__(
        self,
        *,
        ok: builtins.bool = ...,
        message: builtins.str = ...,
        metadata: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
        error: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["error", b"error", "message", b"message", "metadata", b"metadata", "ok", b"ok"]) -> None: ...

global___SetFrequencyResponse = SetFrequencyResponse

@typing.final
class IdlePowerRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DURATION_S_FIELD_NUMBER: builtins.int
    duration_s: builtins.float
    def __init__(
        self,
        *,
        duration_s: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["duration_s", b"duration_s"]) -> None: ...

global___IdlePowerRequest = IdlePowerRequest

@typing.final
class IdlePowerResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DURATION_S_FIELD_NUMBER: builtins.int
    RAILS_FIELD_NUMBER: builtins.int
    N_POWER_SAMPLES_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    duration_s: builtins.float
    n_power_samples: builtins.int
    error: builtins.str
    @property
    def rails(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___RailEnergy]: ...
    def __init__(
        self,
        *,
        duration_s: builtins.float = ...,
        rails: collections.abc.Iterable[global___RailEnergy] | None = ...,
        n_power_samples: builtins.int = ...,
        error: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["duration_s", b"duration_s", "error", b"error", "n_power_samples", b"n_power_samples", "rails", b"rails"]) -> None: ...

global___IdlePowerResponse = IdlePowerResponse

@typing.final
class DraftRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SESSION_ID_FIELD_NUMBER: builtins.int
    GAMMA_FIELD_NUMBER: builtins.int
    BASE_COMMITTED_TOKENS_FIELD_NUMBER: builtins.int
    session_id: builtins.str
    gamma: builtins.int
    base_committed_tokens: builtins.int
    """Absolute committed sequence length expected before drafting, including context tokens."""
    def __init__(
        self,
        *,
        session_id: builtins.str = ...,
        gamma: builtins.int = ...,
        base_committed_tokens: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["base_committed_tokens", b"base_committed_tokens", "gamma", b"gamma", "session_id", b"session_id"]) -> None: ...

global___DraftRequest = DraftRequest

@typing.final
class DraftResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DRAFT_TOKENS_FIELD_NUMBER: builtins.int
    LATENCY_MS_FIELD_NUMBER: builtins.int
    RAILS_FIELD_NUMBER: builtins.int
    N_POWER_SAMPLES_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    latency_ms: builtins.float
    n_power_samples: builtins.int
    error: builtins.str
    @property
    def draft_tokens(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    @property
    def rails(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___RailEnergy]: ...
    def __init__(
        self,
        *,
        draft_tokens: collections.abc.Iterable[builtins.int] | None = ...,
        latency_ms: builtins.float = ...,
        rails: collections.abc.Iterable[global___RailEnergy] | None = ...,
        n_power_samples: builtins.int = ...,
        error: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["draft_tokens", b"draft_tokens", "error", b"error", "latency_ms", b"latency_ms", "n_power_samples", b"n_power_samples", "rails", b"rails"]) -> None: ...

global___DraftResponse = DraftResponse

@typing.final
class VerifyRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SESSION_ID_FIELD_NUMBER: builtins.int
    DRAFT_TOKENS_FIELD_NUMBER: builtins.int
    APPEND_REPLACEMENT_FIELD_NUMBER: builtins.int
    STOP_TOKEN_IDS_FIELD_NUMBER: builtins.int
    BASE_COMMITTED_TOKENS_FIELD_NUMBER: builtins.int
    session_id: builtins.str
    append_replacement: builtins.bool
    base_committed_tokens: builtins.int
    """Absolute committed sequence length expected before verification, including context tokens."""
    @property
    def draft_tokens(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    @property
    def stop_token_ids(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    def __init__(
        self,
        *,
        session_id: builtins.str = ...,
        draft_tokens: collections.abc.Iterable[builtins.int] | None = ...,
        append_replacement: builtins.bool = ...,
        stop_token_ids: collections.abc.Iterable[builtins.int] | None = ...,
        base_committed_tokens: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["append_replacement", b"append_replacement", "base_committed_tokens", b"base_committed_tokens", "draft_tokens", b"draft_tokens", "session_id", b"session_id", "stop_token_ids", b"stop_token_ids"]) -> None: ...

global___VerifyRequest = VerifyRequest

@typing.final
class VerifyResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ACCEPTED_TOKENS_FIELD_NUMBER: builtins.int
    REPLACEMENT_TOKEN_FIELD_NUMBER: builtins.int
    LATENCY_MS_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    RAILS_FIELD_NUMBER: builtins.int
    N_POWER_SAMPLES_FIELD_NUMBER: builtins.int
    APPENDED_REPLACEMENT_FIELD_NUMBER: builtins.int
    COMMITTED_TOKENS_FIELD_NUMBER: builtins.int
    accepted_tokens: builtins.int
    replacement_token: builtins.int
    latency_ms: builtins.float
    error: builtins.str
    n_power_samples: builtins.int
    appended_replacement: builtins.bool
    committed_tokens: builtins.int
    """Absolute committed sequence length after verification, including context tokens."""
    @property
    def rails(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___RailEnergy]: ...
    def __init__(
        self,
        *,
        accepted_tokens: builtins.int = ...,
        replacement_token: builtins.int = ...,
        latency_ms: builtins.float = ...,
        error: builtins.str = ...,
        rails: collections.abc.Iterable[global___RailEnergy] | None = ...,
        n_power_samples: builtins.int = ...,
        appended_replacement: builtins.bool = ...,
        committed_tokens: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["accepted_tokens", b"accepted_tokens", "appended_replacement", b"appended_replacement", "committed_tokens", b"committed_tokens", "error", b"error", "latency_ms", b"latency_ms", "n_power_samples", b"n_power_samples", "rails", b"rails", "replacement_token", b"replacement_token"]) -> None: ...

global___VerifyResponse = VerifyResponse

@typing.final
class GenerateRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SESSION_ID_FIELD_NUMBER: builtins.int
    MAX_NEW_TOKENS_FIELD_NUMBER: builtins.int
    STOP_TOKEN_IDS_FIELD_NUMBER: builtins.int
    session_id: builtins.str
    max_new_tokens: builtins.int
    @property
    def stop_token_ids(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    def __init__(
        self,
        *,
        session_id: builtins.str = ...,
        max_new_tokens: builtins.int = ...,
        stop_token_ids: collections.abc.Iterable[builtins.int] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["max_new_tokens", b"max_new_tokens", "session_id", b"session_id", "stop_token_ids", b"stop_token_ids"]) -> None: ...

global___GenerateRequest = GenerateRequest

@typing.final
class GenerateResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    GENERATED_TOKENS_FIELD_NUMBER: builtins.int
    LATENCY_MS_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    RAILS_FIELD_NUMBER: builtins.int
    N_POWER_SAMPLES_FIELD_NUMBER: builtins.int
    latency_ms: builtins.float
    error: builtins.str
    n_power_samples: builtins.int
    @property
    def generated_tokens(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    @property
    def rails(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___RailEnergy]: ...
    def __init__(
        self,
        *,
        generated_tokens: collections.abc.Iterable[builtins.int] | None = ...,
        latency_ms: builtins.float = ...,
        error: builtins.str = ...,
        rails: collections.abc.Iterable[global___RailEnergy] | None = ...,
        n_power_samples: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["error", b"error", "generated_tokens", b"generated_tokens", "latency_ms", b"latency_ms", "n_power_samples", b"n_power_samples", "rails", b"rails"]) -> None: ...

global___GenerateResponse = GenerateResponse

@typing.final
class InitSessionRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SESSION_ID_FIELD_NUMBER: builtins.int
    CONTEXT_TOKENS_FIELD_NUMBER: builtins.int
    session_id: builtins.str
    @property
    def context_tokens(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    def __init__(
        self,
        *,
        session_id: builtins.str = ...,
        context_tokens: collections.abc.Iterable[builtins.int] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["context_tokens", b"context_tokens", "session_id", b"session_id"]) -> None: ...

global___InitSessionRequest = InitSessionRequest

@typing.final
class InitSessionResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SESSION_ID_FIELD_NUMBER: builtins.int
    CONTEXT_TOKENS_FIELD_NUMBER: builtins.int
    LATENCY_MS_FIELD_NUMBER: builtins.int
    RAILS_FIELD_NUMBER: builtins.int
    N_POWER_SAMPLES_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    session_id: builtins.str
    context_tokens: builtins.int
    latency_ms: builtins.float
    n_power_samples: builtins.int
    error: builtins.str
    @property
    def rails(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___RailEnergy]: ...
    def __init__(
        self,
        *,
        session_id: builtins.str = ...,
        context_tokens: builtins.int = ...,
        latency_ms: builtins.float = ...,
        rails: collections.abc.Iterable[global___RailEnergy] | None = ...,
        n_power_samples: builtins.int = ...,
        error: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["context_tokens", b"context_tokens", "error", b"error", "latency_ms", b"latency_ms", "n_power_samples", b"n_power_samples", "rails", b"rails", "session_id", b"session_id"]) -> None: ...

global___InitSessionResponse = InitSessionResponse

@typing.final
class CommitRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SESSION_ID_FIELD_NUMBER: builtins.int
    ACCEPTED_TOKENS_FIELD_NUMBER: builtins.int
    REPLACEMENT_TOKEN_FIELD_NUMBER: builtins.int
    APPEND_REPLACEMENT_FIELD_NUMBER: builtins.int
    BASE_COMMITTED_TOKENS_FIELD_NUMBER: builtins.int
    session_id: builtins.str
    accepted_tokens: builtins.int
    replacement_token: builtins.int
    append_replacement: builtins.bool
    base_committed_tokens: builtins.int
    """Absolute committed sequence length expected before committing this draft."""
    def __init__(
        self,
        *,
        session_id: builtins.str = ...,
        accepted_tokens: builtins.int = ...,
        replacement_token: builtins.int = ...,
        append_replacement: builtins.bool = ...,
        base_committed_tokens: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["accepted_tokens", b"accepted_tokens", "append_replacement", b"append_replacement", "base_committed_tokens", b"base_committed_tokens", "replacement_token", b"replacement_token", "session_id", b"session_id"]) -> None: ...

global___CommitRequest = CommitRequest

@typing.final
class CommitResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    COMMITTED_TOKENS_FIELD_NUMBER: builtins.int
    LATENCY_MS_FIELD_NUMBER: builtins.int
    RAILS_FIELD_NUMBER: builtins.int
    N_POWER_SAMPLES_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    committed_tokens: builtins.int
    """Absolute committed sequence length after the commit, including context tokens."""
    latency_ms: builtins.float
    n_power_samples: builtins.int
    error: builtins.str
    @property
    def rails(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___RailEnergy]: ...
    def __init__(
        self,
        *,
        committed_tokens: builtins.int = ...,
        latency_ms: builtins.float = ...,
        rails: collections.abc.Iterable[global___RailEnergy] | None = ...,
        n_power_samples: builtins.int = ...,
        error: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["committed_tokens", b"committed_tokens", "error", b"error", "latency_ms", b"latency_ms", "n_power_samples", b"n_power_samples", "rails", b"rails"]) -> None: ...

global___CommitResponse = CommitResponse

@typing.final
class ResetSessionRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SESSION_ID_FIELD_NUMBER: builtins.int
    session_id: builtins.str
    def __init__(
        self,
        *,
        session_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["session_id", b"session_id"]) -> None: ...

global___ResetSessionRequest = ResetSessionRequest

@typing.final
class ResetSessionResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    OK_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    ok: builtins.bool
    error: builtins.str
    def __init__(
        self,
        *,
        ok: builtins.bool = ...,
        error: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["error", b"error", "ok", b"ok"]) -> None: ...

global___ResetSessionResponse = ResetSessionResponse
