"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import abc
import collections.abc
import grpc
import grpc.aio
import typing
import xronos.proto.spec_pb2

_T = typing.TypeVar("_T")

class _MaybeAsyncIterator(collections.abc.AsyncIterator[_T], collections.abc.Iterator[_T], metaclass=abc.ABCMeta): ...

class _ServicerContext(grpc.ServicerContext, grpc.aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

class DrafterStub:
    def __init__(self, channel: typing.Union[grpc.Channel, grpc.aio.Channel]) -> None: ...
    Health: grpc.UnaryUnaryMultiCallable[
        xronos.proto.spec_pb2.HealthRequest,
        xronos.proto.spec_pb2.HealthResponse,
    ]

    SetFrequency: grpc.UnaryUnaryMultiCallable[
        xronos.proto.spec_pb2.SetFrequencyRequest,
        xronos.proto.spec_pb2.SetFrequencyResponse,
    ]

    IdlePower: grpc.UnaryUnaryMultiCallable[
        xronos.proto.spec_pb2.IdlePowerRequest,
        xronos.proto.spec_pb2.IdlePowerResponse,
    ]

    InitSession: grpc.UnaryUnaryMultiCallable[
        xronos.proto.spec_pb2.InitSessionRequest,
        xronos.proto.spec_pb2.InitSessionResponse,
    ]

    Draft: grpc.UnaryUnaryMultiCallable[
        xronos.proto.spec_pb2.DraftRequest,
        xronos.proto.spec_pb2.DraftResponse,
    ]

    Commit: grpc.UnaryUnaryMultiCallable[
        xronos.proto.spec_pb2.CommitRequest,
        xronos.proto.spec_pb2.CommitResponse,
    ]

    ResetSession: grpc.UnaryUnaryMultiCallable[
        xronos.proto.spec_pb2.ResetSessionRequest,
        xronos.proto.spec_pb2.ResetSessionResponse,
    ]

class DrafterAsyncStub:
    Health: grpc.aio.UnaryUnaryMultiCallable[
        xronos.proto.spec_pb2.HealthRequest,
        xronos.proto.spec_pb2.HealthResponse,
    ]

    SetFrequency: grpc.aio.UnaryUnaryMultiCallable[
        xronos.proto.spec_pb2.SetFrequencyRequest,
        xronos.proto.spec_pb2.SetFrequencyResponse,
    ]

    IdlePower: grpc.aio.UnaryUnaryMultiCallable[
        xronos.proto.spec_pb2.IdlePowerRequest,
        xronos.proto.spec_pb2.IdlePowerResponse,
    ]

    InitSession: grpc.aio.UnaryUnaryMultiCallable[
        xronos.proto.spec_pb2.InitSessionRequest,
        xronos.proto.spec_pb2.InitSessionResponse,
    ]

    Draft: grpc.aio.UnaryUnaryMultiCallable[
        xronos.proto.spec_pb2.DraftRequest,
        xronos.proto.spec_pb2.DraftResponse,
    ]

    Commit: grpc.aio.UnaryUnaryMultiCallable[
        xronos.proto.spec_pb2.CommitRequest,
        xronos.proto.spec_pb2.CommitResponse,
    ]

    ResetSession: grpc.aio.UnaryUnaryMultiCallable[
        xronos.proto.spec_pb2.ResetSessionRequest,
        xronos.proto.spec_pb2.ResetSessionResponse,
    ]

class DrafterServicer(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def Health(
        self,
        request: xronos.proto.spec_pb2.HealthRequest,
        context: _ServicerContext,
    ) -> typing.Union[xronos.proto.spec_pb2.HealthResponse, collections.abc.Awaitable[xronos.proto.spec_pb2.HealthResponse]]: ...

    @abc.abstractmethod
    def SetFrequency(
        self,
        request: xronos.proto.spec_pb2.SetFrequencyRequest,
        context: _ServicerContext,
    ) -> typing.Union[xronos.proto.spec_pb2.SetFrequencyResponse, collections.abc.Awaitable[xronos.proto.spec_pb2.SetFrequencyResponse]]: ...

    @abc.abstractmethod
    def IdlePower(
        self,
        request: xronos.proto.spec_pb2.IdlePowerRequest,
        context: _ServicerContext,
    ) -> typing.Union[xronos.proto.spec_pb2.IdlePowerResponse, collections.abc.Awaitable[xronos.proto.spec_pb2.IdlePowerResponse]]: ...

    @abc.abstractmethod
    def InitSession(
        self,
        request: xronos.proto.spec_pb2.InitSessionRequest,
        context: _ServicerContext,
    ) -> typing.Union[xronos.proto.spec_pb2.InitSessionResponse, collections.abc.Awaitable[xronos.proto.spec_pb2.InitSessionResponse]]: ...

    @abc.abstractmethod
    def Draft(
        self,
        request: xronos.proto.spec_pb2.DraftRequest,
        context: _ServicerContext,
    ) -> typing.Union[xronos.proto.spec_pb2.DraftResponse, collections.abc.Awaitable[xronos.proto.spec_pb2.DraftResponse]]: ...

    @abc.abstractmethod
    def Commit(
        self,
        request: xronos.proto.spec_pb2.CommitRequest,
        context: _ServicerContext,
    ) -> typing.Union[xronos.proto.spec_pb2.CommitResponse, collections.abc.Awaitable[xronos.proto.spec_pb2.CommitResponse]]: ...

    @abc.abstractmethod
    def ResetSession(
        self,
        request: xronos.proto.spec_pb2.ResetSessionRequest,
        context: _ServicerContext,
    ) -> typing.Union[xronos.proto.spec_pb2.ResetSessionResponse, collections.abc.Awaitable[xronos.proto.spec_pb2.ResetSessionResponse]]: ...

def add_DrafterServicer_to_server(servicer: DrafterServicer, server: typing.Union[grpc.Server, grpc.aio.Server]) -> None: ...

class VerifierStub:
    def __init__(self, channel: typing.Union[grpc.Channel, grpc.aio.Channel]) -> None: ...
    Health: grpc.UnaryUnaryMultiCallable[
        xronos.proto.spec_pb2.HealthRequest,
        xronos.proto.spec_pb2.HealthResponse,
    ]

    SetFrequency: grpc.UnaryUnaryMultiCallable[
        xronos.proto.spec_pb2.SetFrequencyRequest,
        xronos.proto.spec_pb2.SetFrequencyResponse,
    ]

    IdlePower: grpc.UnaryUnaryMultiCallable[
        xronos.proto.spec_pb2.IdlePowerRequest,
        xronos.proto.spec_pb2.IdlePowerResponse,
    ]

    InitSession: grpc.UnaryUnaryMultiCallable[
        xronos.proto.spec_pb2.InitSessionRequest,
        xronos.proto.spec_pb2.InitSessionResponse,
    ]

    Verify: grpc.UnaryUnaryMultiCallable[
        xronos.proto.spec_pb2.VerifyRequest,
        xronos.proto.spec_pb2.VerifyResponse,
    ]

    Generate: grpc.UnaryUnaryMultiCallable[
        xronos.proto.spec_pb2.GenerateRequest,
        xronos.proto.spec_pb2.GenerateResponse,
    ]

    ResetSession: grpc.UnaryUnaryMultiCallable[
        xronos.proto.spec_pb2.ResetSessionRequest,
        xronos.proto.spec_pb2.ResetSessionResponse,
    ]

class VerifierAsyncStub:
    Health: grpc.aio.UnaryUnaryMultiCallable[
        xronos.proto.spec_pb2.HealthRequest,
        xronos.proto.spec_pb2.HealthResponse,
    ]

    SetFrequency: grpc.aio.UnaryUnaryMultiCallable[
        xronos.proto.spec_pb2.SetFrequencyRequest,
        xronos.proto.spec_pb2.SetFrequencyResponse,
    ]

    IdlePower: grpc.aio.UnaryUnaryMultiCallable[
        xronos.proto.spec_pb2.IdlePowerRequest,
        xronos.proto.spec_pb2.IdlePowerResponse,
    ]

    InitSession: grpc.aio.UnaryUnaryMultiCallable[
        xronos.proto.spec_pb2.InitSessionRequest,
        xronos.proto.spec_pb2.InitSessionResponse,
    ]

    Verify: grpc.aio.UnaryUnaryMultiCallable[
        xronos.proto.spec_pb2.VerifyRequest,
        xronos.proto.spec_pb2.VerifyResponse,
    ]

    Generate: grpc.aio.UnaryUnaryMultiCallable[
        xronos.proto.spec_pb2.GenerateRequest,
        xronos.proto.spec_pb2.GenerateResponse,
    ]

    ResetSession: grpc.aio.UnaryUnaryMultiCallable[
        xronos.proto.spec_pb2.ResetSessionRequest,
        xronos.proto.spec_pb2.ResetSessionResponse,
    ]

class VerifierServicer(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def Health(
        self,
        request: xronos.proto.spec_pb2.HealthRequest,
        context: _ServicerContext,
    ) -> typing.Union[xronos.proto.spec_pb2.HealthResponse, collections.abc.Awaitable[xronos.proto.spec_pb2.HealthResponse]]: ...

    @abc.abstractmethod
    def SetFrequency(
        self,
        request: xronos.proto.spec_pb2.SetFrequencyRequest,
        context: _ServicerContext,
    ) -> typing.Union[xronos.proto.spec_pb2.SetFrequencyResponse, collections.abc.Awaitable[xronos.proto.spec_pb2.SetFrequencyResponse]]: ...

    @abc.abstractmethod
    def IdlePower(
        self,
        request: xronos.proto.spec_pb2.IdlePowerRequest,
        context: _ServicerContext,
    ) -> typing.Union[xronos.proto.spec_pb2.IdlePowerResponse, collections.abc.Awaitable[xronos.proto.spec_pb2.IdlePowerResponse]]: ...

    @abc.abstractmethod
    def InitSession(
        self,
        request: xronos.proto.spec_pb2.InitSessionRequest,
        context: _ServicerContext,
    ) -> typing.Union[xronos.proto.spec_pb2.InitSessionResponse, collections.abc.Awaitable[xronos.proto.spec_pb2.InitSessionResponse]]: ...

    @abc.abstractmethod
    def Verify(
        self,
        request: xronos.proto.spec_pb2.VerifyRequest,
        context: _ServicerContext,
    ) -> typing.Union[xronos.proto.spec_pb2.VerifyResponse, collections.abc.Awaitable[xronos.proto.spec_pb2.VerifyResponse]]: ...

    @abc.abstractmethod
    def Generate(
        self,
        request: xronos.proto.spec_pb2.GenerateRequest,
        context: _ServicerContext,
    ) -> typing.Union[xronos.proto.spec_pb2.GenerateResponse, collections.abc.Awaitable[xronos.proto.spec_pb2.GenerateResponse]]: ...

    @abc.abstractmethod
    def ResetSession(
        self,
        request: xronos.proto.spec_pb2.ResetSessionRequest,
        context: _ServicerContext,
    ) -> typing.Union[xronos.proto.spec_pb2.ResetSessionResponse, collections.abc.Awaitable[xronos.proto.spec_pb2.ResetSessionResponse]]: ...

def add_VerifierServicer_to_server(servicer: VerifierServicer, server: typing.Union[grpc.Server, grpc.aio.Server]) -> None: ...
